version: '3.8'

services:
 dev-db:
  image: postgres:13
  container_name: pg
  ports:
   - "5434:5432"
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 123
   POSTGRES_DB: nest
  networks:
   - project_network

networks:
 project_network:
